title: Qinglong Tian
email: qinglong.tian@uwaterloo.ca
description: Assistant Professor, Department of Statistics and Actuarial Science, University of Waterloo
url: "https://qinglong-tian.github.io"
baseurl: ""
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CLAUDE.md
